"""Constants for the myPV integration."""

from homeassistant.const import (
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
)

DOMAIN = "mypv"

COMM_HUB = "mpv_comm"

CONF_HOSTS = "conf_hosts"
HOST_LIST = "host_list"
MIN_IP = "min_ip"
MAX_IP = "max_ip"
DEV_IP = "dev_ip"
UPDATE_INTERVAL = "update_interval"
CONF_DEFAULT_INTERVAL = 10
CONF_MIN_INTERVAL = 3
CONF_MAX_INTERVAL = 30

SENSOR_TYPES = {
    "device": ["Device", None, "text"],
    "acthor9s": ["Acthor 9s", None, "text"],
    "fwversion": ["Control Unit Fw Version", None, "version"],
    "psversion": ["Power Unit Fw Version", None, "version"],
    "p9sversion": ["Power Unit Fw Version Acthor 9", None, "version"],
    "screen_mode_flag": ["Screen mode", None, "sensor"],
    "status": ["Status", None, "dev_stat"],
    "power": ["Power", UnitOfPower.WATT, "control"],
    "power_elwa2": ["Power ELWA-2", UnitOfPower.WATT, "control"],
    "power_ac9": ["Power AC9", UnitOfPower.WATT, "control"],
    "power_ac9s": ["Power AC9s", UnitOfPower.WATT, "control"],
    "power_act": ["Power", UnitOfPower.WATT, "control"],
    "int_power": ["Energy consumption", UnitOfEnergy.KILO_WATT_HOUR, "sensor"],
    "int_power_elwa2": ["Energy consumption", UnitOfEnergy.KILO_WATT_HOUR, "sensor"],
    "int_power_ac9": ["Energy consumption", UnitOfEnergy.KILO_WATT_HOUR, "sensor"],
    "int_power_ac9s": ["Energy consumption", UnitOfEnergy.KILO_WATT_HOUR, "sensor"],
    "int_power_act": ["Energy consumption", UnitOfEnergy.KILO_WATT_HOUR, "sensor"],
    "intd_power": ["Energy consumption daily", UnitOfEnergy.KILO_WATT_HOUR, "sensor"],
    "intd_power_elwa2": [
        "Energy consumption daily",
        UnitOfEnergy.KILO_WATT_HOUR,
        "sensor",
    ],
    "intd_power_ac9": [
        "Energy consumption daily",
        UnitOfEnergy.KILO_WATT_HOUR,
        "sensor",
    ],
    "intd_power_ac9s": [
        "Energy consumption daily",
        UnitOfEnergy.KILO_WATT_HOUR,
        "sensor",
    ],
    "intd_power_act": [
        "Energy consumption daily",
        UnitOfEnergy.KILO_WATT_HOUR,
        "sensor",
    ],
    "power_solar": ["Power Solar ELWA-2", UnitOfPower.WATT, "sensor"],
    "power_grid": ["Power Grid ELWA-2", UnitOfPower.WATT, "sensor"],
    "boostpower": ["Boost Power", UnitOfPower.WATT, "sensor"],
    "power_solar_act": ["Power from solar", UnitOfPower.WATT, "sensor"],
    "power_grid_act": ["Power from grid", UnitOfPower.WATT, "sensor"],
    "power_solar_ac9": ["Power from solar Acthor 9", UnitOfPower.WATT, "sensor"],
    "power_grid_ac9": ["Power from grid Acthor 9", UnitOfPower.WATT, "sensor"],
    "power1_solar": ["power1_solar", UnitOfPower.WATT, "sensor"],
    "power1_grid": ["power1_grid", UnitOfPower.WATT, "sensor"],
    "power2_solar": ["power2_solar", UnitOfPower.WATT, "sensor"],
    "power2_grid": ["power2_grid", UnitOfPower.WATT, "sensor"],
    "power3_solar": ["power3_solar", UnitOfPower.WATT, "sensor"],
    "power3_grid": ["power3_grid", UnitOfPower.WATT, "sensor"],
    "load_state": ["load_state", None, "sensor"],
    "load_nom": ["load_nom", UnitOfPower.WATT, "sensor"],
    "rel1_out": ["Relais", None, "binary_sensor"],
    "relay_boost": ["Boost relais", None, "binary_sensor"],
    "relay_alarm": ["Alarm relais", None, "binary_sensor"],
    "ww1target": ["Target temperature", UnitOfTemperature.CELSIUS, "sensor"],
    "temp1": ["Temperatur 1", UnitOfTemperature.CELSIUS, "sensor"],
    "temp2": ["Temperatur 2", UnitOfTemperature.CELSIUS, "sensor"],
    "temp3": ["Temperatur 3", UnitOfTemperature.CELSIUS, "sensor"],
    "temp4": ["Temperatur 4", UnitOfTemperature.CELSIUS, "sensor"],
    "boostactive": ["Start Boost", None, "button"],
    "boostactiveoff": ["Stop Boost", None, "button"],
    "legboostnext": ["legboostnext", None, "sensor"],
    "date": ["Date", None, "sensor"],
    "loctime": ["Loctime", None, "sensor"],
    "unixtime": ["Unix time", None, "sensor"],
    "wp_flag": ["wp_flag", None, "binary_sensor"],
    "wp_time1_ctr": ["wp_time1_ctr", None, "sensor"],
    "wp_time2_ctr": ["wp_time2_ctr", None, "sensor"],
    "wp_time3_ctr": ["wp_time3_ctr", None, "sensor"],
    "pump_pwm": ["Pump PWM", None, "sensor"],
    "schicht_flag": ["Schicht", None, "binary_sensor"],
    "act_night_flag": ["Night flag", None, "binary_sensor"],
    "ctrlstate": ["Control source", None, "sensor"],
    "blockactive": ["Block active", None, "binary_sensor"],
    "error_state": ["Error state", None, "sensor"],
    "meter1_id": ["meter1_id", None, "sensor"],
    "meter1_ip": ["meter1_ip", None, "sensor"],
    "meter2_id": ["meter2_id", None, "sensor"],
    "meter2_ip": ["meter2_ip", None, "sensor"],
    "meter3_id": ["meter3_id", None, "sensor"],
    "meter3_ip": ["meter3_ip", None, "sensor"],
    "meter4_id": ["meter4_id", None, "sensor"],
    "meter4_ip": ["meter4_ip", None, "sensor"],
    "meter5_id": ["meter5_id", None, "sensor"],
    "meter5_ip": ["meter5_ip", None, "sensor"],
    "meter6_id": ["meter6_id", None, "sensor"],
    "meter6_ip": ["meter6_ip", None, "sensor"],
    "surplus": ["Surplus", None, "sensor_always"],
    "m0sum": ["m0sum", None, "sensor"],
    "m0l1": ["m0l1", None, "sensor"],
    "m0l2": ["m0l2", None, "sensor"],
    "m0l3": ["m0l3", None, "sensor"],
    "m0bat": ["m0bat", None, "sensor"],
    "m1sum": ["m1sum", None, "sensor"],
    "m1l1": ["m1l1", None, "sensor"],
    "m1l2": ["m1l2", None, "sensor"],
    "m1l3": ["m1l3", None, "sensor"],
    "m1devstate": ["m1devstate", None, "sensor"],
    "m2sum": ["m2sum", None, "sensor"],
    "m2l1": ["m2l1", None, "sensor"],
    "m2l2": ["m2l2", None, "sensor"],
    "m2l3": ["m2l3", None, "sensor"],
    "m2soc": ["m2soc", None, "sensor"],
    "m2state": ["m2state", None, "sensor"],
    "m2devstate": ["m2devstate", None, "sensor"],
    "m3sum": ["m3sum", None, "sensor"],
    "m3l1": ["m3l1", None, "sensor"],
    "m3l2": ["m3l2", None, "sensor"],
    "m3l3": ["m3l3", None, "sensor"],
    "m3soc": ["m3soc", None, "sensor"],
    "m3devstate": ["m3devstate", None, "sensor"],
    "m4sum": ["m4sum", None, "sensor"],
    "m4l1": ["m4l1", None, "sensor"],
    "m4l2": ["m4l2", None, "sensor"],
    "m4l3": ["m4l3", None, "sensor"],
    "m4devstate": ["m4devstate", None, "sensor"],
    "ecarstate": ["ecarstate", None, "sensor"],
    "ecarboostctr": ["ecarboostctr", None, "sensor"],
    "mss2": ["mss2", None, "sensor"],
    "mss3": ["mss3", None, "sensor"],
    "mss4": ["mss4", None, "sensor"],
    "mss5": ["mss5", None, "sensor"],
    "mss6": ["mss6", None, "sensor"],
    "mss7": ["mss7", None, "sensor"],
    "mss8": ["mss8", None, "sensor"],
    "mss9": ["mss9", None, "sensor"],
    "mss10": ["mss10", None, "sensor"],
    "mss11": ["mss11", None, "sensor"],
    "volt_mains": ["Volt L1", UnitOfElectricPotential.VOLT, "sensor"],
    "curr_mains": ["Current L1", UnitOfElectricCurrent.AMPERE, "sensor"],
    "volt_L2": ["Volt L2", UnitOfElectricPotential.VOLT, "sensor"],
    "curr_L2": ["Current L2", UnitOfElectricCurrent.AMPERE, "sensor"],
    "volt_L3": ["Volt L3", UnitOfElectricPotential.VOLT, "sensor"],
    "curr_L3": ["Current L3", UnitOfElectricCurrent.AMPERE, "sensor"],
    "volt_out": ["Volt out", UnitOfElectricPotential.VOLT, "sensor"],
    "freq": ["Frequency", UnitOfFrequency.HERTZ, "sensor"],
    "temp_ps": ["Temp Power Unit", UnitOfTemperature.CELSIUS, "sensor"],
    "fan_speed": ["Fan speed", None, "sensor"],
    "ps_state": ["Power supply state", None, "sensor"],
    "cur_ip": ["IP", None, "ip_string"],
    "cur_sn": ["Subnet mask", None, "ip_string"],
    "cur_gw": ["Gateway", None, "ip_string"],
    "cur_dns": ["DNS", None, "ip_string"],
    "fwversionlatest": ["latest Control Unit Fw Version", None, "version"],
    "psversionlatest": ["latest Power Unit Fw Version", None, "version"],
    "p9sversionlatest": ["latest Power Unit Fw Version Acthor 9", None, "version"],
    "upd_state": ["Control Unit Update State", None, "upd_stat"],
    "upd_files_left": ["Update files left", None, "sensor"],
    "ps_upd_state": ["Power Unit Update State", None, "upd_stat"],
    "p9s_upd_state": ["Acthor 9 Power Unit Update State", None, "upd_stat"],
    "volt_solar": ["Volt solar", UnitOfElectricPotential.VOLT, "sensor"],
}
SETUP_TYPES = {
    # "mainmode": ["Operating Mode", None, "", "sensor"],
    # "mode9s": ["Operating Mode Acthor 9", None, "", "sensor"],
    "devmode": ["Enable Device", None, "switch"],
    "bstmode": ["Enable Boost Mode", None, "switch"],
    "ww1target": ["Target Temperature", None, "number"],
    "ww1boost": ["Boost Min Temperature", None, "number"],
    "ctrl": ["Control type", None, "ctrl_type"],
}
